site_name: ISCC Enhancement Proposals
site_description: 'International Standard Content Code - Enhancement Proposals (IEPs).'
site_author: 'Titusz Pan'
site_url: 'https://ieps.iscc.codes'
docs_dir: ieps

# Repository
repo_name: 'iscc/iscc-ieps'
repo_url: 'https://github.com/iscc/iscc-ieps'
edit_uri: 'edit/main/ieps/'

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom

theme:
  name: material
  custom_dir: ieps/overrides
  logo: images/iscc-logo-icon-white.svg
  favicon: images/iscc-logo-icon-black.svg
  language: en
  font:
    text: Readex Pro
    code: JetBrains Mono
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

plugins:
  - search
  - glightbox
  - add-number:
      strict_mode: False
      order: 2
      excludes:
        - index.md
  - git-revision-date-localized:
      type: iso_date
      locale: en
      enable_creation_date: true
      enabled: true
      exclude:
        - index.md

markdown_extensions:
  - abbr
  - pymdownx.snippets:
      base_path: ["ieps/includes"]
      auto_append: ["abbreviations.md"]
  - tables
  - meta
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Overview: index.md
  - IEP-0000 - IEP Purpose: iep-0000.md
  - IEP-0001 - ISCC Structure: iep-0001.md
  - IEP-0002 - Meta-Code: iep-0002.md
  - IEP-0003 - Text-Code: iep-0003.md
  - IEP-0004 - Image-Code: iep-0004.md
  - IEP-0005 - Audio-Code: iep-0005.md
  - IEP-0006 - Video-Code: iep-0006.md
  - IEP-0007 - Mixed-Code: iep-0007.md
  - IEP-0008 - Data-Code: iep-0008.md
  - IEP-0009 - Instance-Code: iep-0009.md
  - IEP-0010 - ISCC-CODE: iep-0010.md
  - IEP-0011 - ISCC-ID: iep-0011.md
  - IEP-0012 - Metadata: iep-0012.md
  - IEP-0013 - Registry: iep-0013.md
  - IEP-0014 - EVM Registries: iep-0014.md
  - IEP-0015 - DID Method: iep-0015.md
