[project]
name = "iscc-ieps"
version = "0.1.0"
description = "IEPs - ISCC Enhancement Proposals"
authors = [{ name = "Titusz Pan", email = "tp@iscc.io" }]
requires-python = ">=3.12,<3.14"
readme = "README.md"
license = "Apache-2.0"
keywords = [
    "iscc",
    "identifier",
    "media",
    "content",
    "hash",
    "blockchain",
    "similarity",
]
dependencies = [
    "black",
    "mkdocs-material",
    "click==8.2.1",
    "poethepoet",
    "mdformat-gfm",
    "mdformat-tables",
    "mdformat-config",
    "mdformat-black",
    "mdformat-web",
    "mdformat-toc",
    "mdformat_footnote",
    "mdformat_frontmatter",
    "mkdocs-git-revision-date-localized-plugin",
    "mkdocs-add-number-plugin",
    "mkdocs-glightbox",
    "mdformat-mkdocs",
]

[project.urls]
Homepage = "https://ieps.iscc.codes"
Repository = "https://github.com/iscc/iscc-ieps"

[tool.poe.tasks]
format-code = { cmd = "uv run black .", help = "Code style formating with black" }
format-md = { sequence = [
    { cmd = "uv run mdformat --wrap 100 --end-of-line lf --number ." },
    { cmd = "uv run python -m tools.fix_attr_lists" },
], help = "Markdown formating with mdformat" }
build-ieps = { cmd = "uv run python -m tools.build_ieps", help = "Copy README.md to /ieps" }
all = ["format-code", "build-ieps",]

[tool.hatch.build.targets.sdist]
include = ["ieps"]

[tool.hatch.build.targets.wheel]
include = ["ieps"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
